### ISSUE TITLE
Private info into production bundle.

### ISSUE THREAD

**Issue by ghost** [xxczaki/styled-react-boilerplate#2]
After build into `main.{hash}.chunk.js` we get a call function `register` with private info about project directory. Example: `l.register(n,"Button","C:\\Users\\USERNAME\\Desktop\\styled-react-boilerplate\\src\\components\\button.js")`. Its problem of cache react-hot-loader, [issue](https://github.com/gaearon/react-hot-loader/issues/630).

**Comment by xxczaki** [comment]
Should now be fixed :smile:
