### ISSUE TITLE
Use local images

### ISSUE THREAD

**Issue by jvlobo** [xxczaki/styled-react-boilerplate#4]
Hi there!
Is there something that needs to be done to load images from the `public` folder?
I've been trying but I'm not able to get them loaded. It always throws a 404 not found.

**Comment by CRGavrila** [comment]
+1 Also images cannot be resolved when import

**Comment by xxczaki** [comment]
Hi,

I added the FAQ section to the readme, which includes a guide on how to load images :smile:

https://github.com/xxczaki/styled-react-boilerplate#how-to-add--use-static-assets-ex-images
