### ISSUE TITLE
Issue with lib cache group

### ISSUE THREAD

**Issue by hypzeh** [xxczaki/styled-react-boilerplate#5]
## Expected Behaviour

The `npm run start` script  to start running the webpack dev server, and execute the chunking optimisations without throwing an error.

## Actual Behaviour

The following line throws `TypeError: Cannot read property '1' of null`:

https://github.com/xxczaki/styled-react-boilerplate/blob/04d42f7af249d479a4a359e931ab472e9cdb3bcb/webpack.config.js#L76

<details>
<summary>Logs</summary>
<br>

```shell
$ npm run start

> styled-react-boilerplate@1.0.0 start D:\_dev\tmp\styled-react-boilerplate-master
> webpack-dev-server --hot --open --mode development

[hardsource:f19c974b] Writing new cache f19c974b...
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\_dev\tmp\styled-react-boilerplate-master\dist
[hardsource:f19c974b] Tracking node dependencies with: package.json, node_modules/*.
D:\_dev\tmp\styled-react-boilerplate-master\webpack.config.js:76
                                                        return /node_modules\/(.*)/.exec(module.identifier())[1]
                                                                                                             ^

TypeError: Cannot read property '1' of null
```

</details>

## Steps to Reproduce the Problem

1. `npm install`
1. `npm run start`

## Further Notes

- The `npm run build` script seems to be completely fine
- No errors after removing the function

**Comment by xxczaki** [comment]
This issue should no longer occur. Please reopen if necessary :smile:
