### ISSUE TITLE
in production: The "data" argument must be one of type string

### ISSUE THREAD

**Issue by CRGavrila** [xxczaki/styled-react-boilerplate#6]
When building project it gets following error in windows environment:

> ERROR in ./public/icon.png
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type function
    at Hash.update (internal/crypto/hash.js:58:11)
> 

But it will work if remove/comment following in webpack.config:
`
        require('imagemin-webp'),
        require('imagemin-svgo')
`

**Comment by xxczaki** [comment]
This issue should no longer occur. Please reopen if necessary :smile:
